Cherry pick of 6344f37dcfab9c566746505ecd0f36f3e98168b5 failed
stdout:
CONFLICT (add/add): Merge conflict in l10n_uy_edi/views/product_view.xml
Auto-merging l10n_uy_edi/views/product_view.xml
Auto-merging l10n_uy_edi/views/account_move_views.xml
Auto-merging l10n_uy_edi/models/account_move.py
CONFLICT (content): Merge conflict in l10n_uy_edi/models/account_move.py
Auto-merging l10n_uy_edi/models/__init__.py
Auto-merging l10n_uy_edi/data/cfe_template.xml
CONFLICT (content): Merge conflict in l10n_uy_edi/data/cfe_template.xml
Auto-merging l10n_uy_edi/__manifest__.py
CONFLICT (content): Merge conflict in l10n_uy_edi/__manifest__.py

stderr:
18:37:31.335904 git.c:444               trace: built-in: git cherry-pick 6344f37dcfab9c566746505ecd0f36f3e98168b5
error: could not apply 6344f37... [ADD] l10n_uy_edi: New fields required by the dgi were added
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: