Cherry pick of cdf66330d162fb5d25ba74deb5cbf93bc8af21cf failed
stdout:
Auto-merging l10n_uy_account/__manifest__.py
CONFLICT (content): Merge conflict in l10n_uy_account/__manifest__.py

stderr:
11:56:59.319671 git.c:439               trace: built-in: git cherry-pick cdf66330d162fb5d25ba74deb5cbf93bc8af21cf
error: could not apply cdf6633... [IMP] l10n_uy_account: add manual journal type
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: