Cherry pick of 8e24e5a2f1a3ee32a91e6f269f84bdea1ff9d489 failed
stdout:
Auto-merging l10n_uy_edi/views/account_move_views.xml
Auto-merging l10n_uy_edi/models/l10n_uy_cfe.py
Auto-merging l10n_uy_edi/data/cfe_template.xml
CONFLICT (content): Merge conflict in l10n_uy_edi/data/cfe_template.xml
Auto-merging l10n_uy_edi/__manifest__.py
CONFLICT (content): Merge conflict in l10n_uy_edi/__manifest__.py

stderr:
12:23:36.769097 git.c:444               trace: built-in: git cherry-pick 8e24e5a2f1a3ee32a91e6f269f84bdea1ff9d489
error: could not apply 8e24e5a... [ADD] l10n_uy_edi: New fields required by the dgi were added
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: