Cherry pick of 80098dd980f0944574c691897b97d41a5d2aa007 failed
stdout:
CONFLICT (modify/delete): l10n_uy_edi/views/account_move_views.xml deleted in HEAD and modified in 80098dd ([FIX] l10n_uy_edi: Re print PDF button). Version 80098dd ([FIX] l10n_uy_edi: Re print PDF button) of l10n_uy_edi/views/account_move_views.xml left in tree.
CONFLICT (modify/delete): l10n_uy_edi/__manifest__.py deleted in HEAD and modified in 80098dd ([FIX] l10n_uy_edi: Re print PDF button). Version 80098dd ([FIX] l10n_uy_edi: Re print PDF button) of l10n_uy_edi/__manifest__.py left in tree.

stderr:
17:54:45.383327 git.c:444               trace: built-in: git cherry-pick 80098dd980f0944574c691897b97d41a5d2aa007
error: could not apply 80098dd... [FIX] l10n_uy_edi: Re print PDF button
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: